name: Deploy React App

on:
  push:
    branches:
    - master # Trigger deployment on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Set this to your node version or the project version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Connect as sudo user
          sudo su

          # Move to the project directory
          cd /var/www/back-office/htdocs/frontend/

          # Timestamp for the build
          TIMESTAMP=$(date +%F-%T)

          # Create a directory for old builds if it doesn't exist
          mkdir -p test_old_builds test_build

          # Move the current build to the old_builds directory
          if [ -d "build" ]; then
            cp -R build "old_builds/old_build_$TIMESTAMP"
            # mv build "old_builds/old_build_$TIMESTAMP"
          fi

          # Since the entire repo (including the build directory) is transferred
          # to the server by the ssh-action, the 'build' directory will be in the
          # root directory where the SSH command is executed.
          # Now, move the new 'build' directory to the desired location
          mv build ./test_build
